backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "modules" # Used in routes, e.g., /admin/collections/blog
    label: "Modules" # Used in the UI
    folder: "content/modules" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string" , required: true}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date Published", name: "date", widget: "datetime"}
      - {label: "Duration", name: "duration", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "participants" # Used in routes, e.g., /admin/collections/blog
    label: "Participants" # Used in the UI
    folder: "content/participants" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Specialization", name: "specialization", widget: "string"}
      - {label: "Upload Photo", name: "photo", widget: "image"}
      - {label: "Discription", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}